name: Run docker build

on: 
    push

jobs:
    docker-compose:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout repo
            uses: actions/checkout@v4

        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: aman3105
                password: dOC@MAN3105

        -   name: Build and push
            uses: docker/build-push-action@v5
            with:
                push: true
                tags: aman3105/flask-api-core:1.0
